# Generated by Django 4.1.3 on 2022-11-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='case_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
