# Generated by Django 4.1.3 on 2022-11-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_nr', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('arrival_mode', models.IntegerField()),
                ('pain', models.BooleanField(default=False)),
                ('injury', models.BooleanField(default=False)),
                ('mental', models.IntegerField()),
                ('issue', models.TextField()),
                ('pain_rate', models.IntegerField()),
                ('systole', models.IntegerField()),
                ('diastole', models.IntegerField()),
                ('heart_raet', models.IntegerField()),
                ('breathing_rate', models.IntegerField()),
                ('body_temp', models.IntegerField()),
            ],
        ),
    ]
