# Generated by Django 4.1.3 on 2023-01-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_nr', models.IntegerField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('arrival_mode', models.IntegerField()),
                ('pain', models.BooleanField(default=False)),
                ('injury', models.BooleanField(default=False)),
                ('mental', models.IntegerField()),
                ('pain_rate', models.IntegerField()),
                ('systole', models.IntegerField()),
                ('diastole', models.IntegerField()),
                ('heart_raet', models.IntegerField()),
                ('breathing_rate', models.IntegerField()),
                ('body_temp', models.IntegerField()),
                ('process_done', models.BooleanField(default=False)),
                ('archive_date', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
