# Generated by Django 4.1.3 on 2023-01-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='archive_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
