# Generated by Django 4.1.3 on 2022-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='process_done',
            field=models.BooleanField(default=False),
        ),
    ]
