# Generated by Django 4.1.3 on 2022-12-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('beds_count', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
